package personalfinancemanager;

/**
 *
 * @author Geek Squad
 */
public class BudgetNameAndBarPane extends javax.swing.JPanel {

    /**
     * Creates new form BudgetNameAndBarPane
     */
    public BudgetNameAndBarPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budgetNameLabel = new javax.swing.JLabel();
        budgetProgressBar = new javax.swing.JProgressBar();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        budgetNameLabel.setText("Budget name");
        add(budgetNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        budgetProgressBar.setValue(40);
        budgetProgressBar.setString("$120 of $300");
        budgetProgressBar.setStringPainted(true);
        add(budgetProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, 26));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel budgetNameLabel;
    private javax.swing.JProgressBar budgetProgressBar;
    // End of variables declaration//GEN-END:variables
}
